version: "2"

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:14-3.4 # Cambia la imagen a postgis/postgis
    environment:
      POSTGRES_DB: mic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATESTYLE: "ISO,DMY"
      POSTGRES_EXTENSIONS: postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    command: "postgres -c datestyle='ISO,DMY'"
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mic
    links:
      - postgres
    volumes:
      - ./backend:/app
    restart: always

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app

  client-backoffice:
    container_name: cliente-backoffice
    build: ./client-backoffice
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./client-backoffice:/app
